# Generated by Django 6.0.2 on 2026-02-23 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure', models.IntegerField(help_text='Tenure in months')),
                ('purpose', models.CharField(max_length=255)),
                ('credit_check_consent', models.BooleanField(default=False)),
                ('auto_debit_consent', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
