# Generated by Django 6.0.2 on 2026-02-23 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_private_key_user_wallet_address_loanrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=255)),
                ('existing_loan_emis', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
