# Generated by Django 6.0.2 on 2026-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_borrowerfinancialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Borrower', 'Borrower'), ('Lender', 'Lender')], default='Borrower', max_length=20),
        ),
    ]
