# Generated by Django 6.0.2 on 2026-02-23 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_appetite', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], default='Medium', max_length=20)),
                ('total_lending_amount', models.DecimalField(decimal_places=2, help_text='Amount in USDC', max_digits=15)),
                ('time_period_months', models.IntegerField(help_text='Lock-in period in months')),
                ('auto_reinvest', models.BooleanField(default=False)),
                ('withdrawal_preference', models.CharField(choices=[('Monthly Interest', 'Monthly Interest'), ('End of Term', 'End of Term'), ('Manual', 'Manual')], default='Monthly Interest', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
