# Generated by Django 6.0.2 on 2026-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lenderpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredXWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('private_key', models.CharField(max_length=66)),
            ],
        ),
    ]
