# Generated by Django 6.0.2 on 2026-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_credxwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(default='Approved', max_length=20),
        ),
    ]
