# Generated by Django 6.0.2 on 2026-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_address_user_kyc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
    ]
